services:
  lede-build-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lede-build-env
    volumes:
      - /vol1/1000/Projects/lede:/lede
    working_dir: /lede
    restart: unless-stopped